name: Build-and-Deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Checkout Master
      uses: |
        actions/checkout@master
      
    - name: npm install, build
      run: |
        npm install
        npm run changelog
        npm run build --if-present
      env:
        CI: true
        BASE_BRANCH: master
        BRANCH: master
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build --if-present
